language: ruby
dist: trusty
rvm:
  - 2.2
install: gem install asciidoctor-pdf --pre

git:
  depth: 1
branches:
  only:
  - master
addons:
  apt:
    packages:
    - zsh

env:
  global:
  - ENCRYPTION_LABEL: "de1faff15945"
  - COMMIT_AUTHOR_EMAIL: "psprint@zdharma.org"

before_script:
- zsh --version
- >-
    zsh -c 'print -rl -- "ZSH_VERSION: $ZSH_VERSION" "ZSH_PATCHLEVEL: $ZSH_PATCHLEVEL" "OSTYPE: $OSTYPE" "CPUTYPE: $CPUTYPE" "MACHTYPE: $MACHTYPE"'
script:
- make
- make test VERBOSE=1
- make -C zsdoc pdf
- share/deploy_doc.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#zplugin"
    on_success: change # default: always
    on_failure: always # default: always
    skip_join: true
