language: ruby
dist: bionic
rvm:
  - 2.6
install: gem install asciidoctor-pdf --pre

git:
  depth: 1
branches:
  only:
  - master
addons:
  apt:
    packages:
    - zsh
    - mailutils

env:
  global:
  - ENCRYPTION_LABEL: "de1faff15945"
  - COMMIT_AUTHOR_EMAIL: "psprint@zdharma.org"

before_script:
- apt-get install -y zsh
- zsh --version
- >-
    zsh -c 'print -rl -- "ZSH_VERSION: $ZSH_VERSION" "ZSH_PATCHLEVEL: $ZSH_PATCHLEVEL" "OSTYPE: $OSTYPE" "CPUTYPE: $CPUTYPE" "MACHTYPE: $MACHTYPE"'
script:
- git fetch --depth=1 origin tests:tests
- git worktree add test tests
- make
- make -C zsdoc pdf
- share/deploy_doc.sh
- make test VERBOSE=1
- make testB VERBOSE=1
- make testC VERBOSE=1
- make testD VERBOSE=1
- make testE VERBOSE=1

notifications:
  irc:
    channels:
      - "chat.freenode.net#zplugin"
    on_success: change # default: always
    on_failure: change # default: always
    skip_join: true
