site_name: Zplugin Wiki
nav:
- "Introduction":
  - "Introduction": INTRODUCTION.md
- "Ice Modifiers":
  - "Multiple Prompts": Multiple-prompts.md
  - "Example wait Conditions": Example-wait-conditions.md
  - "Installing With Make": Installing-with-make.md
  - "Sourcing Multiple Files": Sourcing-multiple-files.md
  - "Nickname a Plugin or Snippet": id-as.md
  - "Tracking precmd-based Plugins": wrap-track.md
- "Examples":
  - "Example Minimal Setup": Example-Minimal-Setup.md
  - "Example Oh My Zsh Setup": Example-Oh-My-Zsh-setup.md
  - "LS_COLORS Explanation": LS_COLORS-explanation.md
  - "Direnv Explanation": Direnv-explanation.md
  - "Compiling Programs": Compiling-programs.md
  - "Profiling Plugins": Profiling-plugins.md
  - "Gallery": GALLERY.md
- "Zplugin Extensions":
  - "Z-Plugins": Z-PLUGINS.md
  - "z-p-submods": z-p-submods.md
  - "declare-zsh": declare-zsh.md
  - "Crasis": crasis.md
- "Hints": 
  - "Preinstalling Plugins": preinstalling-plugins.md
- "Plugin Standard":
  - "Zsh Plugin Standard": zsh-plugin-standard.md
- "Code Documentation": 
  - "Overview": Code-Documentation.md
  - "zplugin.zsh": zplugin.zsh.md
  - "zplugin-side.zsh": zplugin-side.zsh.md
  - "zplugin-install.zsh": zplugin-install.zsh.md
  - "zplugin-autoload.zsh": zplugin-autoload.zsh.md

theme:
  name: null
  custom_dir: 'docs/theme'
  logo:
    icon: home
  feature:
    tabs: true
markdown_extensions:
  - admonition
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark:
  - pymdownx.smartsymbols:
  - toc:
      permalink: '#'
      separator: '_'
extra_css:
  - css/theme.css
  - css/syntax-highlighting.css
extra_javascript:
  - js/syntax-highlighting.js
  - js/init.js
extra:
  social:
    - type: 'github'
      link: 'https://github.com/zdharma/zplugin'
    - type: 'reddit'
      link: 'https://www.reddit.com/r/zplugin/'
