blank_issues_enabled: true
contact_links:
  - name: â“ GitHub Discussions
    url: https://github.com/zdharma-continuum/zinit/discussions
    about: Please ask and answer questions here
  - name: ğŸ’¬ Gitter
    url: https://gitter.im/zdharma-continuum/community/
    about: Chat with the team
