name: zshelldoc
on: [push]
jobs:
  make-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Install zshelldoc
        run: |
          sudo apt-get install -y zsh
          git clone https://github.com/zdharma-continuum/zshelldoc.git /tmp/zsd.git
          cd /tmp/zsd.git
          sudo make install
          zsd --help

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Install asciidoctor-pdf
        run: |
          gem install asciidoctor-pdf

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: make docs
        run: |
          make doc

      - name: make pdf
        run: |
          make -C doc/zsdoc pdf

      - name: Tar doc/
        run: |
          tar cvzf /tmp/doc.tar.gz doc

      - name: Archive doc.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            /tmp/doc.tar.gz

      - name: Check if docs are up to date
        run: |
          git --no-pager diff

          if ! git --no-pager diff --quiet
          then
            echo "The docs in the repo are not up to date" >&2
            exit 1
          fi
