name: ğŸ“š documentation
on: [push, pull_request, workflow_dispatch]

jobs:
  zshelldoc:
    runs-on: ubuntu-latest
    steps:
      - name: â™¦ï¸ Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: ğŸ“„ Install asciidoctor-pdf
        run: |
          gem install asciidoctor-pdf

      - name: ğŸ“¡ Check out repository
        uses: actions/checkout@v3

      - name: ğŸ‘· Generate zsd
        run: |
          make doc-container
          sudo chown -R "$(id -u):$(id -g)" .

      - name: ğŸ“‡ Generate PDF
        run: |
          make -C doc/zsdoc pdf

      - name: ğŸ—„ï¸ Tar doc/
        run: |
          tar cvzf /tmp/doc.tar.gz doc

      - name: âœ‰ï¸ Upload doc.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            /tmp/doc.tar.gz

      - name: ğŸ•µï¸ Check if the zsd docs need to be updated
        run: |
          if git --no-pager diff --exit-code
          then
            echo "âœ… The zshelldocs are up to date"
          else
            {
              echo "âŒ The zshelldocs in the repo are not up to date"
              echo 'Please regenerate them with $ make doc'
            }
            exit 1
          fi
