name: ðŸ“š documentation
on: [push, pull_request, workflow_dispatch]

jobs:
  zshelldoc:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¦ Install zshelldoc
        run: |
          sudo apt-get install -y zsh
          git clone https://github.com/zdharma-continuum/zshelldoc.git /tmp/zsd.git
          cd /tmp/zsd.git
          sudo make install
          zsd --help

      - name: â™¦ï¸ Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: ðŸ“„ Install asciidoctor-pdf
        run: |
          gem install asciidoctor-pdf

      - name: ðŸ“¡ Check out repository
        uses: actions/checkout@v2

      - name: ðŸ‘· Generate zsd
        run: |
          make doc

      - name: ðŸ“‡ Generate PDF
        run: |
          make -C doc/zsdoc pdf

      - name: ðŸ—„ï¸ Tar doc/
        run: |
          tar cvzf /tmp/doc.tar.gz doc

      - name: âœ‰ï¸ Upload doc.tar.gz
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: |
            /tmp/doc.tar.gz

      - name: ðŸ•µï¸ Check if the zsd docs need to be updated
      # NOTE: We need to run git diff twice here since w/o --quiet it's RC
      # is always 0. The first is to display the diff output, the second one
      # to test whether the diff is empty.
        run: |
          git --no-pager diff
          if git --no-pager diff --quiet
          then
            echo "âœ… The zshelldocs are up to date"
          else
            {
              echo "âŒ The zshelldocs in the repo are not up to date"
              echo 'Please regenerate them with $ make doc'
            } >&2
            exit 1
          fi
