name: Documentation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'zinit*.zsh'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zshelldoc:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repository
        uses: actions/checkout@v3

      - name: re-generate documentation
        run: |
          make doc/container
          sudo chown -R "$(id -u):$(id -g)" .

      - name: check for out-of-date documentation
        run: |
          echo "### Documentation summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          if ! git --no-pager diff --exit-code; then
            echo "::error:: Z-shelldocs are out-of-date." >> $GITHUB_STEP_SUMMARY
            echo 'To regenerate, run `make doc`' >> $GITHUB_STEP_SUMMARY
            exit 1
          else
            echo "::notice:: Z-shelldocs are up-to-date." >> $GITHUB_STEP_SUMMARY
          fi
