name: ğŸ“‘ gh-pages
on:
  push:
    branches:
      - documentation

jobs:
  publish-pages:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¡ Checkout out repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ğŸ Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: ğŸ“¦ Install mkdocs
        run: |
          pip install mkdocs mkdocs-material

      - name: ğŸ¤³ Publish to gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          make gh-pages
