# name: Installer

# concurrency:
#   cancel-in-progress: true
#   group: ${{ github.workflow }}-${{ github.ref }}

# defaults:
#   run:
#     shell: bash

# env:
#   NO_INPUT: true
#   TERM: xterm
#   ZINIT_BRANCH: ${{ github.ref_name }}
#   ZINIT_COMMIT: ${{ github.sha }}
#   ZINIT_REPO: ${{ github.repository }}

# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - .github/workflows/installer.yaml
#       - scripts/**
#       - share/**
#       - zinit*.zsh
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:

#   zinit-installer:

#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: true
#       matrix:
#         annexes: ["with annexes", "no annexes"]
#         os: [macos-latest, ubuntu-latest, windows-latest]

#     steps:

#       - name: check out repository
#         uses: actions/checkout@v3

#       - name: windows dependencies
#         if: runner.os == 'Windows'
#         uses: egor-tensin/setup-cygwin@v3
#         with:
#           platform: x64
#           packages: curl git zsh

#       - name: remove \r
#         if: runner.os == 'Windows'
#         run: sed -i 's/\r$//' scripts/*.sh

#       - name: linux/macos dependencies
#         if: runner.os != 'Windows'
#         run: brew install --force curl subversion unzip xz zsh

#       - name: install
#         run: ./scripts/install.sh

#       - name: verify install
#         run: zsh -silc 'zinit --help'
