name: linting
on: [push, pull_request]
jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: "ğŸ–¨ï¸  Check out repository code"
        uses: actions/checkout@v2

      - name: "ğŸ’¬ Set matrix output"
        id: set-matrix
        run: |
          MATRIX="$(find . -type d -name 'doc' -prune -o -type f -iname '*.zsh' -print | jq -ncR '{"include": [{"file": inputs}]}')"
          echo "MATRIX=${MATRIX}" >&2
          echo "::set-output name=matrix::${MATRIX}"

  lint:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}

    steps:
      - name: "ğŸ–¨ï¸  Check out repository code"
        uses: actions/checkout@v2

      - name: "ğŸ“¦ Install dependencies"
        run: |
          sudo apt install -y zsh

      - name: "ğŸ‘“ zsh -n: ${{ matrix.file }}"
        env:
          ZSH_FILE: ${{ matrix.file }}
        run: |
          zsh -n "${ZSH_FILE}"
